# Generated by Django 2.1.7 on 2019-08-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='curso2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('url_imagen', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=50)),
            ],
        ),
    ]
